ansible-link__deploy_dir: "{{ deploy_dir }}/ansible-link"
ansible-link__deploy_group: "{{ deploy_group }}"
ansible-link__deploy_user: "{{ deploy_user }}"
ansible-link__domain: "ansible-link.{{ domain }}"
ansible_link__inventory_file: "{{ ansible-link__deploy_dir }}/hosts"
ansible-link__network: "{{ network_public }}"
ansible-link__nfs: "{{ nfs }}"
ansible-link__nfs_ip: "{{ nfs_server_ip }}"
ansible-link__state: "started"